Negative Potions Fix
ViaVersion/ViaFabricPlus pull request #570
Opened 2024-09-22 05:06 UTC by FrostFizzie

Negative amplifier potion effects were removed in 1.20.5+ causing some problems playing on older versions such as servers that use negative levitation for a more customizable fall speed, but instead you'll float normally without because the client clamps potion amplifiers.  This ofc fixes that problem when playing on 1.20.4> servers.

2024-09-22 07:07 UTC, RacoonDog requested changes

2024-09-22 07:07 UTC, RacoonDog commented on src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/MixinStatusEffect.java
> +    @Shadow @Final public static int MIN_AMPLIFIER = ProtocolTranslator.getTargetVersion().olderThanOrEqualTo(ProtocolVersion.v1_20_3) ? -255 : 0;
this wont work correctly, since you're setting the value of a constant depending on the value of a mutable config

2024-09-22 07:07 UTC, RacoonDog commented on src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/MixinStatusEffect.java
> +    @Redirect(method = "<init>(Lnet/minecraft/registry/entry/RegistryEntry;IIZZZLnet/minecraft/entity/effect/StatusEffectInstance;)V", at = @At(value = "INVOKE", target = "Lnet/minecraft/util/math/Ma
imo this would be better as a `ModifyArg`

2024-09-23 19:19 UTC, FlorianMichael approved these changes
First of all thank you both @FrostFizzie and @RacoonDog,

I pushed a fix to address styling issues the PR had (e.g unused imports) and also changed the code to just not clamp at all (because that's what MC does when comparing both client source codes

2024-09-23 19:21 UTC, merged