Added support for some movement differences on Bedrock <-> Java
ViaVersion/ViaFabricPlus pull request #645
Opened 2024-12-05 16:07 UTC by Oryxel

- Bedrock doesn't seems to have modifyVelocityZero (0.003/0.005D), the movement appear to just slowly going down until it reaches 0.
- If you moving on both X and Z axis your movement input get multiplied by 1f / Math.sqrt(2), you can get this value by debugging using ProxyPass.

Also this is tested on [here](https://github.com/Oryxel/Boar), current anti-cheat that I'm working on that is incomplete but is good enough to check for (1e-4) movement differences if you just walking around normally.

2024-12-05 23:37 UTC, FlorianMichael requested changes
Beside the styling/general things; RK and I both don't have the time to review/verify this anytime soon and it's also questionable if this should wait for ViaBedrock to get more features/be more usable.

2024-12-05 23:37 UTC, FlorianMichael commented on src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinLivingEntity.java
> +        if (this.sidewaysSpeed != 0 && this.forwardSpeed != 0) {
Would need a check for bedrock version

2024-12-05 23:37 UTC, FlorianMichael commented on src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinLivingEntity.java
> +        }else if (ProtocolTranslator.getTargetVersion().olderThanOrEqualTo(ProtocolVersion.v1_8)) {
```suggestion
        } else if (ProtocolTranslator.getTargetVersion().olderThanOrEqualTo(ProtocolVersion.v1_8)) {
```

2024-12-05 23:37 UTC, FlorianMichael commented on src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinLivingEntity.java
> +            float value = (float) (1F / Math.sqrt(2));
The value could be a static marked with Unique and prefixed with viaFabricPlus$

2024-12-06 15:24 UTC, Oryxel commented
Done, I will leave this here until ViaBedrock to get is more usable.

2024-12-08 14:05 UTC, closed without merging